"""empty message

Revision ID: 3915d804f360
Revises:
Create Date: 2024-08-22 09:06:23.665076

"""

from alembic import op
import sqlalchemy as sa

import migrations_types

# revision identifiers, used by Alembic.
revision = "3915d804f360"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", migrations_types.VectorType(dim=384), nullable=True, comment="hnsw(distance=cosine)"),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("screens")
    # ### end Alembic commands ###
