"""empty message

Revision ID: 893c0d02a0e7
Revises: 3915d804f360
Create Date: 2024-08-23 17:30:27.018377

"""

from alembic import op
import sqlalchemy as sa

import migrations_types

# revision identifiers, used by Alembic.
revision = "893c0d02a0e7"
down_revision = "3915d804f360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "searches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("q", sa.Text(), nullable=False),
        sa.Column("embedding", migrations_types.VectorType(dim=384), nullable=True, comment="hnsw(distance=cosine)"),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("searches")
    # ### end Alembic commands ###
